// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./src/components/auth/index.vue')['default']
    DemoComponent: typeof import('./src/components/demo-component.vue')['default']
    EmailLogin: typeof import('./src/components/auth/email-login.vue')['default']
    SocialLogin: typeof import('./src/components/auth/social-login.vue')['default']
  }
}

export { }
