// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./src/components/auth/index.vue')['default']
    DemoComponent: typeof import('./src/components/demo-component.vue')['default']
    EmailLogin: typeof import('./src/components/auth/email-login.vue')['default']
    Navbar: typeof import('./src/components/navbar/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NResult: typeof import('naive-ui')['NResult']
    NSpace: typeof import('naive-ui')['NSpace']
    NText: typeof import('naive-ui')['NText']
    SocialLogin: typeof import('./src/components/auth/social-login.vue')['default']
    TablerBrandFacebook: typeof import('~icons/tabler/brand-facebook')['default']
    TablerBrandGithub: typeof import('~icons/tabler/brand-github')['default']
    TablerBrandGoogle: typeof import('~icons/tabler/brand-google')['default']
  }
}

export { }
